networks:
  internal:
    driver: bridge
    name: recrutation
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - internal

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - internal

  app:
    image : task:0.0.1-SNAPSHOT
    container_name: recrutation-application
    depends_on:
      - mongodb
    environment:
      - MONGO_DB_HOST=mongodb
    networks:
      - internal
    ports:
      - '8080:8080'
      - '5005:5005'
volumes:
  app:
    driver: local
  mongo:
    driver: local